### ISSUE TITLE
missing `remove attendee api`

### ISSUE THREAD

**Issue by gabrieltong** [fillup/Smx_Simple_Meetings#1]
Hey there , your tool is very useful , thank you !

but I don't find the api to remove an attendee from meeting , do the plugin support this feature ?

**Comment by fillup** [comment]
@gabrieltong Do you mean to remove them from a live meeting? Unfortunately there is no ability to do that that I am aware of. (sorry for delayed response, I didnt get any emails from github and just noticed this now)

**Comment by gabrieltong** [comment]
@fillup thank you all the same , actually , I tracked the response , I found we don't get the `attendeeId` , and that what we need when remove attendee .
