### ISSUE TITLE
hey,fillup,i need you...

### ISSUE THREAD

**Issue by marlonfan** [fillup/Smx_Simple_Meetings#3]
nice to meet you.i would ask...this webex now can work?i look this final time is 2013...
@fillup

**Comment by fillup** [comment]
Hi @MarlonFan yes, it should still work. What service are you wanting to use it with, Meeting Center? The WebEx APIs dont change that much over time, so this library may not support some of their latest features, but it will still do all the core things like scheduling meetings and such.

**Comment by MarlonFan** [comment]
My English is not very good,but thank you very much. It can run it in a sandbox?

**Comment by marlonfan** [comment]
My English is not very good,but thank you very much. It can run it in a sandbox?@fillup

**Comment by fillup** [comment]
@MarlonFan do you already have a WebEx host account? This library integrates with WebEx's APIs to perform the actions and the APIs require you to have a host account. You may be able to get a free trial and test with it though, try this for a 14 day trial: http://mytrial.webex.com/mc-us14.

**Comment by marlonfan** [comment]
Our company change the cisco products.. But thank you very much.@fillup
